CREATE DATABASE esquenta
GO
ALTER DATABASE [esquenta] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [esquenta] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [esquenta] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [esquenta] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [esquenta] SET ARITHABORT OFF 
GO
ALTER DATABASE [esquenta] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [esquenta] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [esquenta] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [esquenta] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [esquenta] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [esquenta] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [esquenta] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [esquenta] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [esquenta] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [esquenta] SET  DISABLE_BROKER 
GO
ALTER DATABASE [esquenta] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [esquenta] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [esquenta] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [esquenta] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [esquenta] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [esquenta] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [esquenta] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [esquenta] SET RECOVERY FULL 
GO
ALTER DATABASE [esquenta] SET  MULTI_USER 
GO
ALTER DATABASE [esquenta] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [esquenta] SET DB_CHAINING OFF 
GO
ALTER DATABASE [esquenta] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [esquenta] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [esquenta] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'esquenta', N'ON'
GO
ALTER DATABASE [esquenta] SET QUERY_STORE = OFF
GO
USE [esquenta]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [esquenta]
GO
/****** Object:  Table [dbo].[Comanda]    Script Date: 27/10/2017 21:32:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comanda](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](255) NULL,
	[CodigoBarras] [varchar](25) NULL,
	EmAberto BIT DEFAULT 0,
 CONSTRAINT [PK_Comanda] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EntradaProduto]    Script Date: 27/10/2017 21:32:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EntradaProduto](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Produto_ID] [int] NULL,
	[Quantidade] [int] NULL,
	[Valor] [decimal](19, 2) NULL,
	[DataEntrada] [datetime] NULL,
 CONSTRAINT [PK_EntradaProduto] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ItemVenda]    Script Date: 27/10/2017 21:32:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ItemVenda](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Venda_ID] [int] NULL,
	[Produto_ID] [int] NULL,
	[Quantidade] [bigint] NULL,
	[DataVenda] [datetime] NULL,
	[Valor] [decimal](19, 2) NULL,
	[ValorTotal] [decimal](19, 2) NULL,
 CONSTRAINT [PK_ItemVenda] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Produto]    Script Date: 27/10/2017 21:32:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Produto](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](255) NULL,
	[Descricao] [nvarchar](255) NULL,
	[Quantidade] [bigint] NULL,
	[CodigoBarras] [varchar](25) NULL,
	[Valor] [decimal](19, 2) NULL,
	[QuantidadeMinima] [int] NULL,
 CONSTRAINT [PK_Produto] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_Produto] UNIQUE NONCLUSTERED 
(
	[CodigoBarras] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProdutoItem]    Script Date: 27/10/2017 21:32:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProdutoItem](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Parent_ID] [int] NULL,
	[Produto_ID] [int] NULL,
	[Quantidade] [int] NULL,
 CONSTRAINT [PK_ProdutoItem] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UC_ProdutoItem] UNIQUE NONCLUSTERED 
(
	[Parent_ID] ASC,
	[Produto_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Venda]    Script Date: 27/10/2017 21:32:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Venda](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Comanda_ID] [int] NULL,
	[DataVenda] [datetime] NULL,
	[ValorTotal] [decimal](19, 2) NULL,
	[ValorDesconto] [decimal](19, 2) NULL,
	[ValorAcrescimo] [decimal](19, 2) NULL,
	[ValorFinal] [decimal](19, 2) NULL,
	EmAberto BIT DEFAULT 0,
	QuantidadeItens INT,
 CONSTRAINT [PK_Venda] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ItemVenda] ADD  DEFAULT (getdate()) FOR [DataVenda]
GO
ALTER TABLE [dbo].[Venda] ADD  DEFAULT (getdate()) FOR [DataVenda]
GO
ALTER TABLE [dbo].[EntradaProduto]  WITH CHECK ADD  CONSTRAINT [FK_EntradaProduto__Produto_ID] FOREIGN KEY([Produto_ID])
REFERENCES [dbo].[Produto] ([ID])
GO
ALTER TABLE [dbo].[EntradaProduto] CHECK CONSTRAINT [FK_EntradaProduto__Produto_ID]
GO
ALTER TABLE [dbo].[ItemVenda]  WITH CHECK ADD  CONSTRAINT [FK_ItemVenda__Produto_ID] FOREIGN KEY([Produto_ID])
REFERENCES [dbo].[Produto] ([ID])
GO
ALTER TABLE [dbo].[ItemVenda] CHECK CONSTRAINT [FK_ItemVenda__Produto_ID]
GO
ALTER TABLE [dbo].[ItemVenda]  WITH CHECK ADD  CONSTRAINT [FK_ItemVenda__Venda_ID] FOREIGN KEY([Venda_ID])
REFERENCES [dbo].[Venda] ([ID])
GO
ALTER TABLE [dbo].[ItemVenda] CHECK CONSTRAINT [FK_ItemVenda__Venda_ID]
GO
ALTER TABLE [dbo].[ProdutoItem]  WITH CHECK ADD  CONSTRAINT [FK_ProdutoItem__Parent_ID] FOREIGN KEY([Parent_ID])
REFERENCES [dbo].[Produto] ([ID])
GO
ALTER TABLE [dbo].[ProdutoItem] CHECK CONSTRAINT [FK_ProdutoItem__Parent_ID]
GO
ALTER TABLE [dbo].[ProdutoItem]  WITH CHECK ADD  CONSTRAINT [FK_ProdutoItem__Produto_ID] FOREIGN KEY([Produto_ID])
REFERENCES [dbo].[Produto] ([ID])
GO
ALTER TABLE [dbo].[ProdutoItem] CHECK CONSTRAINT [FK_ProdutoItem__Produto_ID]
GO
USE [master]
GO
ALTER DATABASE [esquenta] SET  READ_WRITE 
GO
